openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:41301
  description: Generated server url
paths:
  /products/{id}:
    put:
      tags:
      - product-controller
      operationId: updateProductInfo
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProductRq"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProductDto"
    delete:
      tags:
      - product-controller
      operationId: deleteProduct
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
  /products:
    get:
      tags:
      - product-controller
      operationId: getProductList
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductDto"
    post:
      tags:
      - product-controller
      operationId: createProduct
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: object
              properties:
                productInfo:
                  $ref: "#/components/schemas/CreateProductRq"
                images:
                  type: array
                  items:
                    type: string
                    format: binary
              required:
              - productInfo
          multipart/form-data:
            schema:
              type: object
              properties:
                productInfo:
                  $ref: "#/components/schemas/CreateProductRq"
                images:
                  type: array
                  items:
                    type: string
                    format: binary
              required:
              - productInfo
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProductDto"
  /orders:
    get:
      tags:
      - order-controller
      operationId: getFullOrderList
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrderDto"
    post:
      tags:
      - order-controller
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderRq"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/OrderDto"
  /orders/{id}/status:
    patch:
      tags:
      - order-controller
      operationId: updateOrderStatus
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: status
        in: query
        required: true
        schema:
          type: string
          enum:
          - CREATED
          - CANCELLED
          - PROCESSING
          - DELIVERY
          - FINISHED
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/OrderDto"
  /orders/{id}:
    get:
      tags:
      - order-controller
      operationId: getOrderList
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrderDto"
  /images/{id}:
    get:
      tags:
      - image-controller
      operationId: downloadImage
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: binary
components:
  schemas:
    CreateProductRq:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        amount:
          type: integer
          format: int32
        cost:
          type: number
        type:
          type: string
    ImageDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        originalName:
          type: string
        name:
          type: string
        size:
          type: integer
          format: int64
        contentType:
          type: string
        preview:
          type: boolean
    ProductDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        amount:
          type: integer
          format: int32
        cost:
          type: number
        type:
          type: string
        imageInfos:
          type: array
          items:
            $ref: "#/components/schemas/ImageDto"
    CreateOrderRq:
      type: object
      properties:
        clientId:
          type: integer
          format: int64
        productInfos:
          type: array
          items:
            $ref: "#/components/schemas/ProductInfoDto"
    ProductInfoDto:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        productAmount:
          type: integer
          format: int32
    OrderDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        status:
          type: string
          enum:
          - CREATED
          - CANCELLED
          - PROCESSING
          - DELIVERY
          - FINISHED
        totalCost:
          type: number
        clientId:
          type: integer
          format: int64
